url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

collections:
  - apps
    
# Build settings
plugins:
  - jekyll-feed
  - jekyll-postcss
    
css_dir: "assets/css" # defaults to "css"
    
    # Exclude from processing.
    # The following items will not be processed, by default.
    # Any item listed under the `exclude:` key here will be automatically added to
    # the internal "default list".
    #
    # Excluded items can be processed by explicitly listing the directories or
    # their entries' file path in the `include:` list.
    #
exclude:
  - node_modules/
  - yarn.lock
  - postcss.config.js
  - tailwind.config.js
  - package.json
  - README.md